#!/bin/bash

# KAMOLON E-Commerce Auto Setup Script
# This script automatically configures the application for any environment
# Usage: ./setup.sh

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Print colored output
print_info() {
    echo -e "${CYAN}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_header() {
    echo ""
    echo -e "${PURPLE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${PURPLE}║  🍜 KAMOLON E-Commerce - Auto Setup                      ║${NC}"
    echo -e "${PURPLE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

# Check if required commands are available
check_requirements() {
    print_info "Checking requirements..."
    
    local missing_deps=()
    
    if ! command -v docker &> /dev/null; then
        missing_deps+=("docker")
    fi
    
    if ! command -v python3 &> /dev/null && ! command -v python &> /dev/null; then
        missing_deps+=("python3")
    fi
    
    if ! command -v openssl &> /dev/null; then
        missing_deps+=("openssl")
    fi
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        print_error "Missing required dependencies: ${missing_deps[*]}"
        echo ""
        echo "Please install the missing dependencies:"
        echo "  Ubuntu/Debian: sudo apt install docker.io python3 openssl"
        echo "  macOS: brew install docker python openssl"
        exit 1
    fi
    
    print_success "All requirements satisfied"
}

# Generate a secure random string
generate_secret_key() {
    if command -v python3 &> /dev/null; then
        python3 -c 'import secrets; print(secrets.token_urlsafe(50))'
    elif command -v python &> /dev/null; then
        python -c 'import secrets; print(secrets.token_urlsafe(50))'
    else
        # Fallback to openssl
        openssl rand -base64 50 | tr -d "=+/" | cut -c1-50
    fi
}

# Generate a secure database password
generate_db_password() {
    openssl rand -base64 24 | tr -d "=+/" | cut -c1-20
}

# Setup backend .env file
setup_backend_env() {
    print_info "Configuring backend environment..."
    
    if [ -f .env ]; then
        print_warning ".env already exists, skipping..."
        return
    fi
    
    if [ ! -f .env.example ]; then
        print_error ".env.example not found!"
        exit 1
    fi
    
    # Copy template
    cp .env.example .env
    
    # Generate secure credentials
    local secret_key=$(generate_secret_key)
    local db_password=$(generate_db_password)
    local db_user="kamolon_user_$(openssl rand -hex 4)"
    
    # Update .env file with generated values
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|DJANGO_SECRET_KEY=.*|DJANGO_SECRET_KEY=$secret_key|g" .env
        sed -i '' "s|ecommerce_user|$db_user|g" .env
        sed -i '' "s|ecommerce_secure_2024|$db_password|g" .env
    else
        # Linux
        sed -i "s|DJANGO_SECRET_KEY=.*|DJANGO_SECRET_KEY=$secret_key|g" .env
        sed -i "s|ecommerce_user|$db_user|g" .env
        sed -i "s|ecommerce_secure_2024|$db_password|g" .env
    fi
    
    print_success "Backend .env configured with secure credentials"
    
    # Save admin credentials info
    echo "# Auto-generated credentials" > .credentials
    echo "DB_USER=$db_user" >> .credentials
    echo "DB_PASSWORD=$db_password" >> .credentials
    chmod 600 .credentials
}

# Setup frontend .env.local file
setup_frontend_env() {
    print_info "Configuring frontend environment..."
    
    local frontend_env="frontend/.env.local"
    
    if [ -f "$frontend_env" ]; then
        print_warning "frontend/.env.local already exists, skipping..."
        return
    fi
    
    # Create frontend .env.local
    cat > "$frontend_env" << 'EOF'
# Frontend Environment Configuration
# Auto-generated by setup.sh

# API Base URL (change in production)
NEXT_PUBLIC_API_BASE_URL=http://localhost:8001/api

# Media Base URL (change in production)
NEXT_PUBLIC_MEDIA_BASE_URL=http://localhost:8001
EOF
    
    print_success "Frontend .env.local created"
}

# Setup mini-app .env file
setup_miniapp_env() {
    print_info "Configuring mini-app environment..."
    
    local miniapp_env="mini-app/.env"
    
    if [ -f "$miniapp_env" ]; then
        print_warning "mini-app/.env already exists, skipping..."
        return
    fi
    
    # Create mini-app .env
    cat > "$miniapp_env" << 'EOF'
# Mini-App Environment Configuration
# Auto-generated by setup.sh

# API Base URL (change in production)
VITE_API_BASE_URL=http://localhost:8001/api
EOF
    
    print_success "Mini-app .env created"
}

# Display final instructions
show_final_instructions() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  ✅ Auto-Setup Complete!                                  ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    print_info "Next steps:"
    echo ""
    echo "  1. Start the application:"
    echo -e "     ${CYAN}make setup${NC}  (or 'make up' if already set up before)"
    echo ""
    echo "  2. Create admin user:"
    echo -e "     ${CYAN}make superuser${NC}"
    echo ""
    echo "  3. Access the application:"
    echo -e "     Frontend:  ${GREEN}http://localhost:3000${NC}"
    echo -e "     Admin:     ${GREEN}http://localhost:8001/admin/${NC}"
    echo -e "     Mini-App:  ${GREEN}http://localhost:3001${NC}"
    echo ""
    print_warning "Your database credentials are saved in .credentials file (keep it safe!)"
    echo ""
}

# Main execution
main() {
    print_header
    
    # Check if we're in the right directory
    if [ ! -f "manage.py" ]; then
        print_error "This script must be run from the project root directory!"
        exit 1
    fi
    
    check_requirements
    
    echo ""
    print_info "Setting up KAMOLON E-Commerce..."
    echo ""
    
    setup_backend_env
    setup_frontend_env
    setup_miniapp_env
    
    show_final_instructions
}

# Run main function
main
